Repository ActoKids/api, pull requests merged in 2019-03, with the labels that each got.

#43 Removed extraneous and outdated files; Remain in Git backlog
  demo_page/.gitignore
  demo_page/README.md
  demo_page/package.json
  demo_page/public/favicon.ico
  demo_page/public/index.html
  demo_page/public/manifest.json
  demo_page/src/App.js
  demo_page/src/TimeStamp.js
  demo_page/src/index.css
  demo_page/src/index.js
  demo_page/src/serviceWorker.js
  demo_page/yarn.lock
  json/event.json
  lambda/getDateData/index.js
  lambda/getEventById/index.js
  lambda/getEvents/index.js
  lambda/pingAPIFunction/index.js
  lambda/putDateData/index.js
  sprint-1-travis-database-research/DocumentDB_Lambda_Test/rest-api/.serverless/cloudformation-template-create-stack.json
  sprint-1-travis-database-research/DocumentDB_Lambda_Test/rest-api/.serverless/cloudformation-template-update-stack.json
  sprint-1-travis-database-research/DocumentDB_Lambda_Test/rest-api/.serverless/rest-api.zip
  sprint-1-travis-database-research/DocumentDB_Lambda_Test/rest-api/.serverless/serverless-state.json
  sprint-1-travis-database-research/DocumentDB_Lambda_Test/rest-api/variables.env
  sprint-2-dynamodb-deleteItem/cloud-function.js
  sprint-2-dynamodb-deleteItem/curl-delete-demo
Labels: API Team

#57 Updated Swagger for issue #49 and added inclusive parameter
  swagger/actokids.yaml
  swagger/event_model.json
Labels: API Team, enhancement

#58 GitHub structure update
  lambda/events/get/index.js
  lambda/events/post/index.js
  lambda/events_id/delete/index.js
  lambda/events_id/get/index.js
  lambda/events_id/put/index.js
  travis-sprint3/events/package-lock.json
  travis-sprint3/events/package.json
Labels: API Team, enhancement

#60 Added package.json so uuid-validate will work and updated lambda
  lambda/events_id/delete/index.js
  lambda/events_id/delete/package-lock.json
  lambda/events_id/delete/package.json
Labels: API Team, Sprint 5

#59 Alex feature/post fixes
  lambda/events/post/index.js
  swagger/actokids.yaml
  swagger/event_model.json
Labels: API Team, Sprint 5

#63 Sprint5 fixes, inplementing is-uuid library
  lambda/events/get/index.js
  lambda/events_id/get/index.js
  lambda/events_id/get/package-lock.json
  lambda/events_id/get/package.json
Labels: API Team, Sprint 5

#67 This is a TravisCI test commit
  lambda/events/post/index.js
Labels: Sprint 5, enhancement

#68 PUT Method Feature Merge
  lambda/events_id/put/index.js
  lambda/events_id/put/package-lock.json
  lambda/events_id/put/package.json
  package-lock.json
  package.json
Labels: API Team, Sprint 5

#70 added delete.zip to lambda delte path so node_modules would be included
  .travis.yml
  lambda/events_id/delete/delete.zip
  lambda/events_id/delete/index.js
  lambda/events_id/delete/package-lock.json
  lambda/events_id/delete/package.json
Labels: API Team, Sprint 5

#72 Changed file structure to include zip folder with node modules
  lambda/events_id/get/get.zip
  lambda/events_id/get/index.js
  lambda/events_id/get/package-lock.json
  lambda/events_id/get/package.json
Labels: API Team
