Repository ActoKids/api, pull requests merged in 2019-02, with the labels that each got.

#9 code for implementing POST method
  .travis.yml
  lambda/POST.js
  lambda/event_model.json
  package.json
Labels: API Team, Sprint 2

#8 completed v1.0 of the swagger file
  swagger/actokids.yaml
Labels: API Team

#22 updates to the event model for API Gateway
  lambda/POST.js
  lambda/event_model.json
Labels: API Team, enhancement

#21 Swagger Updates
  swagger/actokids.yaml
Labels: API Team, enhancement

#13 Travis sprint 2 code
  .gitignore
  sprint-1-travis-database-research/DocumentDB_Lambda_Test/rest-api/.serverless/cloudformation-template-create-stack.json
  sprint-1-travis-database-research/DocumentDB_Lambda_Test/rest-api/.serverless/cloudformation-template-update-stack.json
  sprint-1-travis-database-research/DocumentDB_Lambda_Test/rest-api/.serverless/rest-api.zip
  sprint-1-travis-database-research/DocumentDB_Lambda_Test/rest-api/.serverless/serverless-state.json
  sprint-1-travis-database-research/DocumentDB_Lambda_Test/rest-api/variables.env
  sprint-2-dynamodb-deleteItem/cloud-function.js
  sprint-2-dynamodb-deleteItem/curl-delete-demo
Labels: API Team, Sprint 2

#28 Alex feature/sprint3 post logs
  lambda/POST.js
  swagger/README.txt
Labels: API Team, Sprint 3

#33 updated/moved event model
  swagger/event_model.json
Labels: API Team, enhancement

#14 Sprint 2 - Code for GET events all/by Id
  lambda/getEventById/index.js
  lambda/getEvents/index.js
Labels: API Team, Sprint 2

#32 Sprint 3 - Code with Logging for GET events all/by id
  lambda/getEventById.js
  lambda/getEvents.js
Labels: API Team, Sprint 3

#7 Karens features 2 json
  json/event.json
Labels: API Team

#34 Jon feature/ping sprint3
  lambda/ping.js
Labels: API Team, Sprint 3

#23 inital commit of simpler lambda function for ping API
  lambda/ping.js
Labels: API Team, Sprint 2

#35 Jon feature/ping api
  demo_page/.gitignore
  demo_page/README.md
  demo_page/package.json
  demo_page/public/favicon.ico
  demo_page/public/index.html
  demo_page/public/manifest.json
  demo_page/src/App.js
  demo_page/src/TimeStamp.js
  demo_page/src/index.css
  demo_page/src/index.js
  demo_page/src/serviceWorker.js
  demo_page/yarn.lock
  lambda/pingAPIFunction/index.js
Labels: API Team

#36 Read/Write Lambda for DynamoDB demo
  lambda/getDateData/index.js
  lambda/putDateData/index.js
Labels: API Team
